include:
  - local: "jobs/deploy.yaml"
  - local: "jobs/rules.yaml"
  - local: "jobs/build.yaml"

.global-variables:
  variables:
    SSH_USER: "$ENV_SSH_USER"
    SSH_HOST: "$ENV_SSH_HOST"
    SSH_PRIVATE_KEY_BASE64: "$ENV_PRIVATE_KEY_BASE64"

stages:
  - build
  - deploy

build:
  stage: build
  extends:
    - .build
    - .rules-merge-or-main

deploy:
  stage: deploy
  needs:
    - build
  extends:
    - .docker_run
    - .global-variables
    - .rules-main
  variables:
    OPT_DOCKER: "-p 80:80"

